USE [JTDDB]

CREATE TABLE [ATC].[ATCJobTaskItemKSAO_2](
	[Unique ID] [varchar](300) NULL,
	[Scalar] [varchar](300) NULL,
	[Statement] [varchar](300) NULL,
	[A/SA/T/ST/S/E] [varchar](300) NULL,
	[K1.3 Safety culture] [varchar](300) NULL,
	[K5.1 Human cognitive/K5.2physical performance limitations] [varchar](300) NULL,
	[K5.3 Team concept] [varchar](300) NULL,
	[K8.6/7 Impact on operations] [varchar](300) NULL,
	[K17.2 Reasons for traffic management initiatives] [varchar](300) NULL,
	[K17.4 Strategies for managing traffic management initiatives] [varchar](300) NULL,
	[K18.15/17/18 Facility traffic flows] [varchar](300) NULL,
	[K21.1 Types of separation standards] [varchar](300) NULL,
	[K21.2 Separation minima] [varchar](300) NULL,
	[K21.3 Conflict resolution strategies] [varchar](300) NULL,
	[K21.4 Operational and personal impact of loss of separation] [varchar](300) NULL,
	[K22.2 Duty priorities] [varchar](300) NULL,
	[K22.3 Scanning strategies] [varchar](300) NULL,
	[K23.2/3 Visual flight rule (VFR) flight following] [varchar](300) NULL,
	[K24.8 Visual flight rule (VFR) arrival] [varchar](300) NULL,
	[K24.9/10 Practice approaches] [varchar](300) NULL,
	[K24.10/11 Arrival sequence] [varchar](300) NULL,
	[K25.1 Departure sequence] [varchar](300) NULL,
	[K25.6 Visual flight rule (VFR) departures] [varchar](300) NULL,
	[K27.1 Types of ground emergency or unusual operations] [varchar](300) NULL,
	[K27.2 Types of in-flight emergency or unusual operations] [varchar](300) NULL,
	[K27.5 Emergency assistance techniques] [varchar](300) NULL,
	[K27.6 Coordination requirements] [varchar](300) NULL,
	[K27.7 Notification requirements] [varchar](300) NULL,
	[Sk1, Oral Communication/Sk2, Written] [varchar](300) NULL,
	[Sk3,Active Listening] [varchar](300) NULL,
	[Sk4, Task Switching] [varchar](300) NULL,
	[Sk5, Attention Switching] [varchar](300) NULL,
	[Sk6, Interruption Recovery] [varchar](300) NULL,
	[Sk15, High Workload Recognition] [varchar](300) NULL,
	[Sk16, Performance Monitoring] [varchar](300) NULL,
	[Sk17, Task Prioritization] [varchar](300) NULL,
	[Sk18, Task Timing] [varchar](300) NULL,
	[Sk19, Composure Maintenance] [varchar](300) NULL,
	[Sk21, Shared Responsibility Position Teamwork] [varchar](300) NULL,
	[Sk22, Inter-position Teamwork] [varchar](300) NULL,
	[Sk23, Coordination] [varchar](300) NULL,
	[Sk24, Cue Recognition/ Comprehension] [varchar](300) NULL,
	[Sk25, Service Orientation] [varchar](300) NULL,
	[Sk27, Operational Comprehension] [varchar](300) NULL,
	[Sk29, Facility Monitoring (inter and intra facility monitoring)] [varchar](300) NULL,
	[Sk33, Separation Strategy Development/ Sk34, Selection] [varchar](300) NULL,
	[Sk35, Separation Strategy Implementation] [varchar](300) NULL,
	[Sk36, Sequencing Strategy Development] [varchar](300) NULL,
	[Sk37, Sequencing Strategy Selection/ Sk38, Implementation] [varchar](300) NULL,
	[Sk39, Spacing Strategy Development] [varchar](300) NULL,
	[Sk40, Spacing Strategy Selection] [varchar](300) NULL,
	[Sk41, Spacing Strategy Implementation] [varchar](300) NULL,
	[Sk42, Conflict Identification] [varchar](300) NULL,
	[Sk43, Conflict Resolution Strategy Development] [varchar](300) NULL,
	[Sk44, Conflict Resolution Strategy Selection] [varchar](300) NULL,
	[Sk45, Conflict Resolution Strategy Implementation] [varchar](300) NULL,
	[Sk48, Current Weather Assessment] [varchar](300) NULL,
	[Sk49,  Weather Projection] [varchar](300) NULL,
	[Sk50, Weather Strategy Development] [varchar](300) NULL,
	[Sk51,  Weather Strategy Selection] [varchar](300) NULL,
	[Sk52, Weather Strategy Implementation] [varchar](300) NULL,
	[Sk56,  Emergency Recognition] [varchar](300) NULL,
	[Sk57,  Emergency Response Development/ 58, Selection] [varchar](300) NULL,
	[Sk59,  Emergency Response Implementation] [varchar](300) NULL,
	[FileName] [varchar](300) NULL,
	[RowNumber] [varchar](500) NULL
	)
  