USE [JTDDB]

--Drop Table if it already exists in the database
IF OBJECT_ID('[ATC].[ATCJobTaskItemKSAO]', 'U') IS NOT NULL 
  DROP TABLE [ATC].[ATCJobTaskItemKSAO]; 

GO 
--Create ATC KSAO Import Table
CREATE TABLE [ATC].[ATCJobTaskItemKSAO]
(
[ATCJobTaskItemKSAOID] int Identity(1,1) NOT NULL,
[Unique ID] varchar(8),
[Scalar Number] varchar(300),
[Statement] int,
[A/SA/T/ST/S/E] varchar(1),
[K1.1 FAA organizational structure] varchar(1),
[K1.2 Evolution of air traffic control (ATC)] varchar(1),
[K1.3 Safety culture] varchar(1),
[K1.4 NextGen initiative] varchar(1),
[K1.6 Employee representation] varchar(1),
[K2.1 Decoding facility identifiers] varchar(1),
[K2.2 Types of ATC facilities] varchar(1), 
[K2.3 Roles of each facility type] varchar(1),
[K2.4 Types of ATCS positions in each facility type] varchar(1),
[K2.5 ATCS responsibilities for each position in each facility type] varchar(1),
[K2.6 Types of Traffic Management Unit (TMU) positions] varchar(1),
[K2.7 Traffic Management Unit (TMU) responsibilities] varchar(1),
[K2.8 Automated Flight Service Station (AFSS)] varchar(1),
[K3.1 Aeromedical requirements] varchar(1),
[K3.2 Training requirements] varchar(1),
[K3.3 Credentialing requirements] varchar(1),
[K3.4 Certification requirements] varchar(1),
[K4.1 Aircraft aerodynamics] varchar(1),
[K4.2 Wake turbulence] varchar(1),
[K4.3 Speed regimes (low speed, crusing, high speed)] varchar(1),
[K4.4 Phases of flight] varchar(1),
[K5.1 Human cognitive/K5.2physical performance limitations] varchar(1),
[K5.3 Team concept] varchar(1),
[K5.4 ATC automation] varchar(1),
[K6.1 National geography] varchar(1),
[K6.2 International geography] varchar(1),
[K6.3 Types of obstructions] varchar(1),
[K6.4 Types of altitude references] varchar(1),
[K6.5 Types of distance metrics (NM, SM)] varchar(1),
[K7.1 Air route structure] varchar(1),
[K7.2 Types of navigation aids (NAVAIDS)] varchar(1),
[K7.3 Types of navigation] varchar(1),
[K7.4 Aeronautical charts] varchar(1),
[K7.5 Compass properties] varchar(1),
[K7.6 Geo-referencing] varchar(1),
[K7.7 Compulsory position reporting] varchar(1),
[K7.8 Terrain features] varchar(1),
[K8.1 Atmospheric properties] varchar(1),
[K8.2 Sources of weather information] varchar(1),
[K8.3 Weather terminology] varchar(1),
[K8.4 Weather features] varchar(1),
[K8.5 Weather observation (taking the weather observation)] varchar(1),
[K8.5/6 Weather data interpretation] varchar(1),
[K8.6/7 Impact on operations] varchar(1),
[K8.7/8 Impact on flight/aircraft] varchar(1),
[K8.8/9 Pilot Report (PIREP) solicitation requirements] varchar(1),
[K8.9/10 Weather information recording] varchar(1),
[K8.10/11 Weather information dissemination requirements] varchar(1),
[K8.11/12 Weather minimums] varchar(1),
[K9.1 Types of surveillance systems] varchar(1),
[K9.2 Fundamentals] varchar(1),
[K9.3 Components] varchar(1),
[K9.4 Utility] varchar(1),
[K9.5 Limitations] varchar(1),
[K10.1 Types of communication systems] varchar(1),
[K10.2 Fundamentals] varchar(1),
[K10.3 Components] varchar(1),
[K10.4 Utility] varchar(1),
[K10.5 Limitations] varchar(1),
[K11.1 Categories] varchar(1),
[K11.2 Weight classes] varchar(1),
[K11.3 Designators] varchar(1),
[K11.4 Performance characteristics] varchar(1),
[K11.5 Identification features] varchar(1),
[K11. 5/6 Avionics] varchar(1),
[K12.1 Types of flight operations] varchar(1),
[K12.2 Types of surface operations] varchar(1),
[K12.3 Flight rules] varchar(1),
[K12.4 Altimeter setting criteria] varchar(1),
[K12.5 Aircraft transponder modes] varchar(1),
[K13.1 Decoding airport identifiers] varchar(1),
[K13.2 Components of airport diagram] varchar(1),
[K13.3 Movement versus non-movement area] varchar(1),
[K13.2/4 Services and equipment] varchar(1),
[K13.5 Types of signage] varchar(1),
[K13.3/6 Types of airport lighting] varchar(1),
[K14.1 Types of aeronautical publications and ATC procedures and directives] varchar(1),
[K14.2 Purpose of aeronautical publications and ATC procedures and directives] varchar(1),
[K14.3 Authoritative source of the information] varchar(1),
[K14.4 Location and format of current version] varchar(1),
[K14.5 Subject areas contained in each ATC publication] varchar(1),
[K14.6 Types of sensitive documents] varchar(1),
[K15.1 Airspace classification] varchar(1),
[K15.2 Air defense identification zone (ADIZ)] varchar(1),
[K15.3 ARTCC delegated airspace concept] varchar(1),
[K15.4 Special Activity Airspace] varchar(1),
[K15.5 Flight information region (FIR)] varchar(1),
[K16.1 Types of flight plans] varchar(1),
[K16.2 Required components] varchar(1),
[K16.3 Filing process] varchar(1),
[K16.4 Evaluation strategies] varchar(1),
[K16.5 Flight plan processing] varchar(1),
[K16.6 Flight plan data display methods] varchar(1),
[K17.1 Purpose of traffic management units] varchar(1),
[K17.2 Reasons for traffic management initiatives] varchar(1),
[K17.3 Types of traffic management initiatives] varchar(1),
[K17.4 Strategies for managing traffic management initiatives] varchar(1),
[K18.1 Facility identifier] varchar(1), 
[K18.2 Facility level] varchar(1),
[K18.3 Physical location] varchar(1),
[K18.4 Facility/airport contact information] varchar(1),
[K18.5 Airport diagram (Tower & TRACON)] varchar(1),
[K18.5/6 Facility radio frequencies] varchar(1), 
[K18.6/7 Local navigation aids (NAVAIDS)] varchar(1),
[K18.8 Airport services (Tower & TRACON)] varchar(1),
[K18.7/9 Airspace dimensions] varchar(1),
[K18.8/10 Adjacent airspace] varchar(1),
[K18.9/11 Sector configurations] varchar(1),
[K18.10/12 Airport configurations] varchar(1),
[K18.11/13 Local geography] varchar(1),
[K18.12/14 Impact of local topography on flight] varchar(1),
[K18.13/15 Local obstructions/ obstacles] varchar(1),
[K18.14/16 Local weather patterns] varchar(1),
[K18.17 Tower blind spots] varchar(1),
[K18.15/17/18 Facility traffic flows] varchar(1),
[K18.19 Local traffic patterns] varchar(1),
[K18.16/18/20 Areas with high potential for confliction (hot spots)] varchar(1),
[K18.17/19/21 Facility specific directives and procedures] varchar(1),
[K18.18/20/22 Airspace coordination procedures] varchar(1),
[K19.1 Types of tools and equipment] varchar(1),
[K19.2 Functionality of tools and equipment] varchar(1),
[K19.3 Operation of tools and equipment] varchar(1),
[K19.4 Interpretation of information provided] varchar(1),
[K19.5 Limitations] varchar(1),
[K19.6 Degradation indicators] varchar(1),
[K19.7 Minor troubleshooting] varchar(1),
[K19.8 Backup systems] varchar(1),
[K19.9 Interoperability (exchanging information between systems)] varchar(1),
[K20.1 Types of ATC communications] varchar(1),
[K20.2 Components of each type of communication] varchar(1),
[K20.3 Proper phraseology] varchar(1),
[K20.4 Roles and responsibilities of communicators] varchar(1),
[K20.5 Communication procedures] varchar(1),
[K21.1 Types of separation standards] varchar(1),
[K21.2 Separation minima] varchar(1),
[K21.3 Conflict resolution strategies] varchar(1),
[K21.4 Operational and personal impact of loss of separation] varchar(1),
[K22.1 Types of air traffic services] varchar(1),
[K22.2 Duty priorities] varchar(1),
[K22.3 Scanning strategies] varchar(1),
[K22.4 Procedures for composing clearances and control] varchar(1), 
[K22.5 Application of separation standards] varchar(1),
[K22.6 Radar services procedures] varchar(1),
[K22.7 Nonradar procedures] varchar(1),
[K22.8 Conformance assurance] varchar(1),
[K22.9 Course trend information] varchar(1),
[K22.10 Strategies for severe weather avoidance] varchar(1),
[K22.11 Transfer of control requirements] varchar(1),
[K22.12 Transfer of communication requirements] varchar(1),
[K22.13 Approach control service] varchar(1),
[K22.14 Notice to Airmen (NOTAM)] varchar(1),
[K23.1 Aircraft Management Information System (AMIS)] varchar(1),
[K23.1/2 Direction finding (DF) services] varchar(1),
[K23.2/3 Visual flight rule (VFR) flight following] varchar(1),
[K23.3/4 Flight information service (FIS)] varchar(1),
[K23.4 Glidepath trend information (Tower & TRACON)] varchar(1),
[K23.5 Uncontrolled aircraft] varchar(1),
[K23.6 Nonparticipating aircraft (TRACON & En Route)] varchar(1),
[K23.6 Tower en route control service (Tower)] varchar(1),
[K24.1 Approach/arrival information] varchar(1),
[K24.2 Instrument approaches] varchar(1),
[K24.3 Arrival routes] varchar(1),
[K24.4 Conventional standard terminal arrival routes (STARs)] varchar(1),
[K24.5 Area navigation (RNAV-enabled) arrival routes] varchar(1),
[K24.6 Visual approaches] varchar(1),
[K24.7 Missed approaches] varchar(1),
[K24.8 Visual flight rule (VFR) arrival] varchar(1),
[K24.9 Continual descent approach (CDA)/Optimized] varchar(1),
[K24.9 Continuous descent operations] varchar(1),
[K24.9/10 Practice approaches] varchar(1),
[K24.10/11 Arrival sequence] varchar(1),
[K24.11 Landing operations] varchar(1),
[K25.1 Departure sequence] varchar(1),
[K25.2 Taxi and departure routes] varchar(1),
[K25.3 Departure information] varchar(1),
[K25.4 Conventional standard instrument departures (SIDs)] varchar(1),
[K25.5 Area navigation (RNAV-enabled) departure routes] varchar(1),
[K25.6 Visual flight rule (VFR) departures] varchar(1),
[K25.7 Missed approach procedures] varchar(1),
[K26.1 Types of special operations] varchar(1),
[K26.2 Required clearances and control instructions] varchar(1),
[K26.3 Coordination requirements] varchar(1),
[K26.4 Notification requirements] varchar(1),
[K27.1 Types of ground emergency or unusual operations] varchar(1),
[K27.2 Types of in-flight emergency or unusual operations] varchar(1),
[K27.3 Required clearances and control instructions] varchar(1),
[K27.4 Search and rescue] varchar(1),
[K27.5 Emergency assistance techniques] varchar(1),
[K27.6 Coordination requirements] varchar(1),
[K27.7 Notification requirements] varchar(1),
[K27.8 Reporting requirements] varchar(1),
[Sk1, Oral Communication/Sk2, Written] varchar(1),
[Sk3,Active Listening] varchar(1), 
[Sk4, Task Switching] varchar(1),
[Sk5, Attention Switching] varchar(1),
[Sk6, Interruption Recovery] varchar(1),
[Sk7, Information Location] varchar(1), 
[Sk8, Decoding/Sk9, Encoding] varchar(1),
[Sk10, Reading Comprehension] varchar(1),
[Sk11, Information Filtering] varchar(1),
[Sk12, Rule Application] varchar(1), 
[Sk13, Basic Math Operations] varchar(1),
[Sk14, Principle Application] varchar(1),
[Sk15, High Workload Recognition] varchar(1),
[Sk16, Performance Monitoring] varchar(1),
[Sk17, Task Prioritization] varchar(1), 
[Sk18, Task Timing] varchar(1),
[Sk19, Composure Maintenance] varchar(1),
[Sk20, Position Relief Briefings] varchar(1),
[Sk21, Shared Responsibility Position Teamwork] varchar(1),
[Sk22, Inter-position Teamwork] varchar(1),
[Sk23, Coordination] varchar(1),
[Sk24, Cue Recognition/ Comprehension] varchar(1),
[Sk25, Service Orientation] varchar(1),
[Sk26, Strategic Scanning] varchar(1),
[Sk27, Operational Comprehension] varchar(1),
[Sk28, Object Projection] varchar(1), 
[Sk29, Facility Monitoring (inter and intra facility monitoring)] varchar(1),
[Sk30, Flight Strip Utilization (Air Traffic Flight Data Utilization)] varchar(1),
[Sk31, Spatial Information Application] varchar(1),
[Sk32, Object Identification and Position Establishment] varchar(1),
[Sk33, Separation Strategy Development/ Sk34, Selection] varchar(1),
[Sk35, Separation Strategy Implementation] varchar(1),
[Sk36, Sequencing Strategy Development] varchar(1),
[Sk37, Sequencing Strategy Selection/ Sk38, Implementation] varchar(1),
[Sk39, Spacing Strategy Development] varchar(1),
[Sk40, Spacing Strategy Selection] varchar(1),
[Sk41, Spacing Strategy Implementation] varchar(1),
[Sk42, Conflict Identification] varchar(1),
[Sk43, Conflict Resolution Strategy Development] varchar(1),
[Sk44, Conflict Resolution Strategy Selection] varchar(1),
[Sk45, Conflict Resolution Strategy Implementation] varchar(1),
[Sk46, Advisories/ Alerts Utilization] varchar(1),
[Sk47, Weather Data Interpretation] varchar(1),
[Sk48, Current Weather Assessment] varchar(1),
[Sk49,  Weather Projection] varchar(1),
[Sk50, Weather Strategy Development] varchar(1),
[Sk51,  Weather Strategy Selection] varchar(1),
[Sk52, Weather Strategy Implementation] varchar(1),
[Sk53,  Tool & Equipment Operation (includes keyboarding)] varchar(1),
[Sk54,  Tool & Equipment Status Recognition] varchar(1),
[Sk55,  Tool & Equipment Degradation/ Failure Response] varchar(1),
[Sk56,  Emergency Recognition] varchar(1),
[Sk57,  Emergency Response Development/ 58, Selection] varchar(1),
[Sk59,  Emergency Response Implementation] varchar(1),
[FileName] [varchar](300) NULL,
[InsertBy] [varchar](50) NULL,
[InsertDT] [datetime] NULL,
[UpdateBy] [varchar](50) NULL,
[UpdateDT] [datetime] NULL)