USE [JTDDB]

--Drop Table if it already exists in the database
IF OBJECT_ID('[TechOps].[SpecificJobTaskItem]', 'U') IS NOT NULL 
  DROP TABLE [TechOps].[SpecificJobTaskItem]; 
GO 

CREATE TABLE [TechOps].[SpecificJobTaskItem](
	[JobTaskItemID] [int] IDENTITY(1,1) NOT NULL,
	[JTA Scalar] [varchar](12) NOT NULL,
	[Task Statement] [varchar](300) NULL,
	[DL] [int] NULL,
	[DP] [int] NULL,
	[I] [int] NULL,
	[F] [int] NULL,
	[Knowledge or Performance] [varchar](11) NULL,
	[StatementLevel] [varchar](12) NULL,
	[Knowledge Proficiency] [varchar](1) NULL,
	[Performance Proficiency] [varchar](1) NULL,
	[Calculated Instructional Method] [varchar](7) NULL,
	[Initial Training Priority Rating] [varchar](6) NULL,
	[Refresher Training Priority Rating] [varchar](6) NULL,
	[Tech Ops Specialist - Automation (TOS-A)] [varchar](1) NULL,
	[Tech Ops Specialist - Environmental (TOS-E)] [varchar](1) NULL,
	[Tech Ops Specialist - Navigation (TOS-N)] [varchar](1) NULL,
	[Tech Ops Specialist - Surveillance (TOS-S)] [varchar](1) NULL,
	[Tech Ops Specialist - Communication (TOS-C)] [varchar](1) NULL,
	[Specific, Cross Functiona, Specific Specific] [varchar](16) NULL,
	[Tech Ops Managers (TO-M)] [varchar](1) NULL,
	[Tech Ops Suprevisors (TO-S)] [varchar](1) NULL,
	[Technician in Depth (TID)] [varchar](1) NULL,
	[Service Operation Center (SOC)] [varchar](1) NULL,
	[Operation Control Center - Specialist (OCC-S)] [varchar](1) NULL,
	[Operation Control Center - Team Leader (OCC-T)] [varchar](1) NULL,
	[Second Level Engineering (SLE)] [varchar](1) NULL,
	[Orders/Manuals/Procedures/Instructions] [varchar](400) NULL,
	[SME Delivery Method] [varchar](9) NULL,
	[Instructional Time] [varchar](20) NULL,
	[K1.1 Aircraft accidents] [varchar](200) NULL,
	[K1.2 FAA orders/directives (6000.15x, 6030.45x, 6000.30x)] [varchar](200) NULL,
	[K1.3 Reference materials -Maintenance alerts] [varchar](200) NULL,
	[K1.4 Reference materials -TechNet] [varchar](200) NULL,
	[K1.5 Reference materials - Notices] [varchar](200) NULL,
	[K1.6 Certification] [varchar](200) NULL,
	[K1.7 FSEP (Facilities Service Equipment Program)] [varchar](200) NULL,
	[K1.8 FRD (Faculty Reference Data modifications and documentation)] [varchar](200) NULL,
	[K1.9 HAZMAT policy] [varchar](200) NULL,
	[K1.10 Logistics] [varchar](200) NULL,
	[K1.11 FAA regulations] [varchar](200) NULL,
	[K1.12 FAA organizational structure] [varchar](200) NULL,
	[K1.13 Training programs] [varchar](200) NULL,
	[K1.14 documentation and logging of activities] [varchar](200) NULL,
	[K1.15 Safety] [varchar](200) NULL,
	[K1.16 NAS architecture (air traffic flow, air traffic control functions )] [varchar](200) NULL,
	[K1.17 Labor relations (Union Contract Provisions)] [varchar](200) NULL,
	[K1.18 Control centers roles and responsibilities] [varchar](200) NULL,
	[K1.19 Coordination (internal and external)] [varchar](200) NULL,
	[K1.20 Security requirements] [varchar](200) NULL,
	[K2.1 Redundant systems and services] [varchar](200) NULL,
	[K2.2 Electronics fundamentals and principles] [varchar](200) NULL,
	[K2.3 Electro-mechanical theory] [varchar](200) NULL,
	[K2.4 Engineering mathematics] [varchar](200) NULL,
	[K2.5 System relationships] [varchar](200) NULL,
	[K2.6 Validate system integrity] [varchar](200) NULL,
	[K2.7 Operations and application of software/firmware] [varchar](200) NULL,
	[K2.8 Operational theory of NAS systems/subsystems (i.e., Radar, Communication, Navigational)] [varchar](200) NULL,
	[K2.9 Equipment evaluation -NASTEP (National Airspace System Technical Evaluation Program)] [varchar](200) NULL,
	[K2.10 Equipment evaluation - IOAs (Independent Operational Testing)] [varchar](200) NULL,
	[K2.11 Equipment evaluation - JAI (Joint Acceptance Inspection)] [varchar](200) NULL,
	[K2.12 NAVAID systems] [varchar](200) NULL,
	[K2.13 Satellite communications] [varchar](200) NULL,
	[K2.14 RFI (Radio Frequency Interference)] [varchar](200) NULL,
	[K2.15 Airport operations] [varchar](200) NULL,
	[K2.16 Shutdown and “notice to airmen” procedures] [varchar](200) NULL,
	[K2.17 Facility restoration levels] [varchar](200) NULL,
	[K2.18 Flight check procedures] [varchar](200) NULL,
	[K2.19 Technical discrepancies (e.g., NCPs, PTRs, and HDRs)] [varchar](200) NULL,
	[K2.20 Trend analysis] [varchar](200) NULL,
	[K2.21 Remote maintenance monitoring (RMM/MASS)] [varchar](200) NULL,
	[K2.22 Service delivery (interrelationships between Terminal, GNAS and Center)] [varchar](200) NULL,
	[K2.23 Diagnostics and testing] [varchar](200) NULL,
	[K2.24 Systems theory and analysis] [varchar](200) NULL,
	[K2.25 Antennas and transmission lines] [varchar](200) NULL,
	[K2.26 RDAS (Radar Data Analysis Specialist)] [varchar](200) NULL,
	[K3.1 Electricity] [varchar](200) NULL,
	[K3.2 Power generation and distribution systems] [varchar](200) NULL,
	[K3.3 Heating, ventilation, air conditioning, (HVAC) and controls] [varchar](200) NULL,
	[K3.4 Lighted aids] [varchar](200) NULL,
	[K4.1 Federal telecommunication  infrastructure for  operations] [varchar](200) NULL,
	[K5.1 OSHA requirements] [varchar](200) NULL,
	[K5.2 Military coordination] [varchar](200) NULL,
	[K5.3 NFPA (National Fire Protection Agency) policy (national electric code)] [varchar](200) NULL,
	[K5.4 Coaching and teaching] [varchar](200) NULL,
	[K5.5 Agency coordination] [varchar](200) NULL,
	[K5.6 Weather reporting systems] [varchar](200) NULL,
	[K6.1 Technical computer basics - personal  computer hardware/software fundamentals (Includes internet security)] [varchar](200) NULL,
	[K6.2 Technical computer basics -networking principles] [varchar](200) NULL,
	[K6.3 Technical computer basics - circuit service requests (CSR) for network or telecommunication services] [varchar](200) NULL,
	[K6.4 Technical  computer basics - software to meet system/network requirements] [varchar](200) NULL,
	[K6.5 Technical computer basics - hardware & software platforms] [varchar](200) NULL,
	[K6.6 Technical computer advanced -database and systems management] [varchar](200) NULL,
	[K6.7 Technical computer advanced -Internet Protocol (IP) routings] [varchar](200) NULL,
	[K6.8 Technical computer advanced -systems administration] [varchar](200) NULL,
	[Sk1.1 Upward reporting] [varchar](200) NULL,
	[Sk1.2 Professional telephone techniques] [varchar](200) NULL,
	[Sk1.3 Radio protocol] [varchar](200) NULL,
	[Sk1.4 Formal briefings] [varchar](200) NULL,
	[Sk1.5 Technical writing] [varchar](200) NULL,
	[Sk1.6 Command of language] [varchar](200) NULL,
	[Sk2.1 Professional courtesy &  interpersonal relations] [varchar](200) NULL,
	[Sk3.1 Operating motor vehicles] [varchar](200) NULL,
	[Sk3.2 Climbing] [varchar](200) NULL,
	[Sk3.3 Hand tools/test equipment] [varchar](200) NULL,
	[Sk4.1 Direct technical workforce] [varchar](200) NULL,
	[Sk4.2 Work activities] [varchar](200) NULL,
	[Sk4.3 Resources (include people, money, and material)] [varchar](200) NULL,
	[Sk5.1 troubleshooting] [varchar](200) NULL,
	[Sk5.2 Data] [varchar](200) NULL,
	[Sk5.3 Networking] [varchar](200) NULL,
	[Sk5.4 Blueprints] [varchar](200) NULL,
	[FileName] [varchar](300) NOT NULL,
	[FileRow] [varchar](200) NULL,
	[InsertBy] [varchar](50) NULL,
	[InsertDT] [datetime] NULL,
	[UpdateBy] [varchar](50) NULL,
	[UpdateDT] [datetime] NULL)
GO

ALTER TABLE [TechOps].[SpecificJobTaskItem]
    ADD CONSTRAINT pk_mySpecificJobTaskItem PRIMARY KEY ([JTA Scalar], [FileName])
GO

SET ANSI_PADDING OFF
GO


